// app/api/register/route.ts
import { NextResponse } from "next/server";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { name, email, phone, eventTitle, imageUrl } = body;

    // console.log("Incoming request body:", body);
    console.log("Image URL sent to email:", imageUrl);

    if (!name || !email || !eventTitle) {
      console.warn("Missing required fields");
      return NextResponse.json({ error: "Missing fields" }, { status: 400 });
    }

    // Admin notification
    const { error: adminError } = await resend.emails.send({
      from: "Church Events <info@internationaldisciples.com>",
      to: ["info@internationaldisciples.com"],
      subject: `📩 New Registration: ${eventTitle}`,
      html: `
        <div style="font-family: sans-serif; padding: 16px; background-color: #f9fafb; border-radius: 8px;">
          <h2 style="color: #802E2F;">New Event Registration</h2>
          <p><strong>Event:</strong> ${eventTitle}</p>
          <p><strong>Name:</strong> ${name}</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Phone:</strong> ${phone || "Not provided"}</p>
          <hr style="margin: 16px 0;" />
          <p style="font-size: 12px; color: #6b7280;">This email was automatically generated by the church event registration system.</p>
        </div>
      `,
    });

    if (adminError) {
      console.error("Admin email error:", adminError);
      return NextResponse.json(
        { error: adminError.message || "Failed to notify admin" },
        { status: 500 }
      );
    }

    // User confirmation
    const { error: userError } = await resend.emails.send({
      from: "Church Events <info@internationaldisciples.com>",
      to: [email],
      subject: `✅ You're Registered for ${eventTitle}`,
      html: `
        <div style="font-family: sans-serif; padding: 24px; background-color: #f1f5f9; border-radius: 8px;">
          <h1 style="color: #15803d; font-size: 20px; margin-bottom: 12px;">🎉 Thank You for Registering!</h1>
          <p>Hi <strong>${name}</strong>,</p>
          <p>We're excited to confirm your registration for:</p>
          <h2 style="color: #802E2F;">${eventTitle}</h2>
          ${imageUrl ? `<img src="${imageUrl}" alt="${eventTitle}" style="width: 100%; max-width: 500px; border-radius: 8px; margin: 16px 0;" />` : ""}
          <p><strong>Your Details:</strong></p>
          <ul style="margin-left: 16px;">
            <li><strong>Name:</strong> ${name}</li>
            <li><strong>Email:</strong> ${email}</li>
            <li><strong>Phone:</strong> ${phone || "Not provided"}</li>
          </ul>
          <p style="margin-top: 24px;">We look forward to seeing you there!</p>
          <hr style="margin: 20px 0;" />
          <p style="font-size: 12px; color: #6b7280;">This is a confirmation email from International Disciples Church.</p>
        </div>
      `,
    });

    if (userError) {
      console.error("User email error:", userError);
      return NextResponse.json(
        { error: userError.message || "Failed to send confirmation" },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true });
  } catch (err: unknown) {
    const error = err instanceof Error ? err : new Error("Unknown error");

    console.error("Unexpected error in /api/register:", error);
    return NextResponse.json(
      { error: error.message || "Internal server error" },
      { status: 500 }
    );
  }
}
